# Generated by Django 4.0.2 on 2022-05-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_remove_booksmodel_subject_alter_booksmodel_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='subject',
            field=models.IntegerField(choices=[(1, 'Prospect'), (2, 'Lead'), (3, 'Customer')], default=1),
        ),
    ]
