# Generated by Django 4.0.2 on 2022-05-26 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0005_simplebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=200)),
                ('subject', models.IntegerField(choices=[(1, 'C'), (2, 'Java'), (3, 'Python')], default=1)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksapp.booksmodel')),
            ],
        ),
    ]
